config/routes.rb
RubyCourseProject::Application.routes.draw do

  resources :creatives do
    resources :chapters
  end

  get "home/index"
  post 'switch_theme/' => 'home#switch_theme'

  devise_for :users

  root 'home#index'

  get 'search/tag/' => 'search#tag'
  get 'search/text/' => 'search#text'

  post 'vote/' => 'vote#change_vote', as: :vote

  get 'tags/start_with' => 'tags#start_with'

  get 'user/:id' => 'user#show', as: :user
  get 'admin' => 'user#admin'
  post 'user/:id' => 'user#update'
  delete 'user/:id/delete' => 'user#delete'

  get 'creatives/:id/reorder_chapters' => 'creatives#reorder_chapters'

end

app/models/creative.rb
class Creative < ActiveRecord::Base
  belongs_to :user
  has_and_belongs_to_many :tags
  has_many :chapters, dependent: :destroy
  has_many :votes, dependent: :destroy
  validates :title, :description, presence: true
  after_save :increase_user_amount
  before_destroy :decrease_user_amount

  private 
    def increase_user_amount
      user.creatives_num += 1
      user.save
    end

    def decrease_user_amount
      user.creatives_num -= 1
      user.save
    end
end

app/controllers/creatives_controller.rb
class CreativesController < ApplicationController
  before_action :set_creative, only: [:show, :edit, :update, :destroy, :reorder_chapters]
  before_action :check_rights, only: [:edit, :update, :destroy, :reorder_chapters]
  before_action :reload_cache, only: [:update, :destroy, :reorder_chapters]

  # GET /creatives
  # GET /creatives.json
  def index
    @creatives = Creative.paginate(:page => params[:page])
  end

  # GET /creatives/1
  # GET /creatives/1.json
  def show
    renderer = Redcarpet::Render::HTML.new(:filter_html => true)
    @markdown = Redcarpet::Markdown.new(renderer, :autolink => true)
  end

  # GET /creatives/new
  def new
    @creative = Creative.new
  end

  # GET /creatives/1/edit
  def edit
    respond_to do |format|
      format.html { render "edit" }
      format.json { render "_form.html", :layout => false }
    end
  end

  # POST /creatives
  # POST /creatives.json
  def create
    @creative = Creative.new({ :user_id => current_user.id }.merge(creative_params))
    respond_to do |format|
      if @creative.save
        add_tags_to_creative
        format.html { redirect_to @creative, notice: 'Creative was successfully created.' }
        format.json { render action: 'show', status: :created, location: @creative }
      else
        format.html { render action: 'new' }
        format.json { render json: @creative.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /creatives/1
  # PATCH/PUT /creatives/1.json
  def update
    delete_tags_from_creative
    add_tags_to_creative
    respond_to do |format|
      if @creative.update(creative_params)
        format.html { redirect_to @creative, notice: 'Creative was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @creative.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /creatives/1
  # DELETE /creatives/1.json
  def destroy
    delete_tags_from_creative
    @creative.destroy
    respond_to do |format|
      format.html { redirect_to creatives_url }
      format.json { head :no_content }
    end
  end

  def reorder_chapters
    new_order = params[:order].scan(/\d+/)
    chapters = @creative.chapters
    set_new_order(chapters, new_order)
    render :nothing => true
  end

  private
    def set_creative
      @creative = Creative.find(params[:id])
    end

    def creative_params
      params.require(:creative).permit(:title, :description)
    end

    def check_rights
      authorize! :update, @creative
    end

    def string_of_tags_to_array
      string_tags = params[:tags]
      return string_tags.scan(/[A-Za-zа-яА-Я\d]+/)
    end

    def add_tags_to_creative
      string_of_tags_to_array.each do |string_tag|
        tag = Tag.get_or_create(string_tag)
        @creative.tags << tag
      end
    end

    def delete_tags_from_creative
      @creative.tags.to_a.each do |tag|
        tag.decrease
        @creative.tags.delete(tag)
      end
    end

    def set_new_order(chapters, new_order)
      new_order.each.with_index do |i, position|
        chapter = chapters.find_by(:id => i.to_i)
        chapter.order = position
        chapter.save
      end
    end

    def reload_cache
      expire_fragment([:creative, :show, @creative.id])
    end

end

app/helpers/creatives_helper.rb
module CreativesHelper
end

app/views/creatives/_form.html.erb
<%= form_for(@creative) do |f| %>
  <% if @creative.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@creative.errors.count, "error") %> prohibited this creative from being saved:</h2>

      <ul>
      <% @creative.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label t("creative.title") %>
    <%= f.text_field :title, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label t("creative.description") %>
    <%= f.text_area :description, :class => "form-control", :rows => 6 %>
  </div>

  <div class="form-group">
    <%= f.label t("creative.tag") %>
    <input type="text" class="form-control tags" placeholder="<%= t('creative.enter_tags') %>" name="tags" data-role="tagsinput" 
        value="<% @creative.tags.each do |tag| %><%= tag.value %>,<% end %>"/>
  </div>
  <div class="actions">
    <%= f.submit t("creative.submit"), :class => "btn btn-primary btn-block"  %>
  </div>
<% end %>

<%= javascript_include_tag "tags_input" %>

app/views/creatives/edit.html.erb
<div class="main-content">
    <div class="alert alert-success notification-fixed">
            
    </div>

    </div>
    <div class="page-header">
        <h1><%= t("creative.edit_header") %><small> | <%= link_to t("creative.show"), @creative %></small></h1>
    </div>
    
    <div class="col-md-8">
        <div class="well">
            <%= render 'form' %>
        </div>
    </div>
    <div class="col-md-4">
        <h4 align="center">
            <%= t("creative.creative_info") %>
        </h4>
        <div class="list-group">
            <a class="list-group-item item" >
                <h4 class="list-group-item-heading"><%= @creative.title %></h4>
            </a>
        </div>
        <h4 align="center">
            <%= t("creative.chapters") %>
        </h4>
        <div id="chapters" class="list-group">
            <% @creative.chapters.sort_by{|e| e[:order]}.each do |chapter| %>
                <a id=<%= chapter.order %> class="list-group-item item" data-id=<%= chapter.id %>>
                    <h4 class="list-group-item-heading">
                        <%= chapter.title %>
                        <button class="btn btn-danger btn-xs pull-right">del</button>
                    </h4>
                </a>
            <% end %>
        </div>
        <div class="list-group">
            <a class="list-group-item add" >
                <h4 class="list-group-item-heading">
                    <span class="glyphicon glyphicon-plus"></span>
                    <%= t("creative.add_new") %>
                </h4>
            </a>
        </div>
    </div>
</div>


<script>
    newItem = "<a class='list-group-item item active'><h4 class='list-group-item-heading'>New chapter<button class='btn btn-danger btn-xs pull-right'>del</button></h4></a>"
    creativeUrl = "/creatives/<%= @creative.id %>/reorder_chapters"
    chapterUrl = "/creatives/<%= @creative.id %>/chapters/"
    creativeEditUrl = "/creatives/<%= @creative.id %>/edit.json"
</script>
<%= javascript_include_tag "creatives" %>

app/views/creatives/index.html.erb
<div class="main-content">
    <div class="page-header">
        <h1>Listing creatives</h1>
    </div>

    <%= render "shared/creatives" %>
</div>

app/views/creatives/new.html.erb
<div class="page-header">
    <h1><%= t("creative.new") %></h1>
</div>
<div class="col-md-7">
    <div class="well">
        <%= render 'form' %>
    </div>
</div>

app/views/creatives/show.html.erb
<% if notice %>
    <div class="alert alert-dismissable alert-success">
        <button type="button" class="close" data-dismiss="alert">×</button>
        <%= notice %>
    </div>
<% end %>

<div class="creative">
    <div class="page-header">
        <h1>
            <%= @creative.title %>
            <% if can? :update, @creative %>
            <small> 
                | <%= link_to t("creative.edit"), edit_creative_path(@creative) %> |
                <%= link_to t("creative.destroy"), @creative, method: :delete, data: { confirm: 'Are you sure?' } %>
            </small>
            <% end %>
        </h1>
    </div>
    <% cache([:creative, :show, params[:id]], skip_digest: true) do %>
    <blockquote><%= @creative.description %></blockquote>
    <% @creative.chapters.sort_by{|e| e[:order]}.each do |chapter| %>
        <h2><%= chapter.title %></h2>
        <%= @markdown.render(chapter.content).html_safe %>
    <% end %>

    <div class="creative-footer"> 
        <span class="glyphicon glyphicon-calendar"></span><a><%= @creative.created_at.strftime("%F") %></a>
        <span class="glyphicon glyphicon-user"></span>
        <%= link_to @creative.user.username, "/user/" + @creative.user.id.to_s %>
        <span class="glyphicon glyphicon-tags"></span>
        <% @creative.tags.each do |tag| %>
            <%= link_to tag.value, search_tag_path + "/?q=" + tag.value %>
        <% end %>
        <span id=<%= @creative.id %> class="vote-button btn btn-default btn-xs pull-right">
            <span class="glyphicon glyphicon-thumbs-up"></span>
            <span id="vote"><%= @creative.num_of_votes %></span>
        </span>  
    </div>
    <% end %>
</div>