config/routes.rb
RubyCourseProject::Application.routes.draw do

  resources :creatives do
    resources :chapters
  end

  get "home/index"
  post 'switch_theme/' => 'home#switch_theme'

  devise_for :users

  root 'home#index'

  get 'search/tag/' => 'search#tag'
  get 'search/text/' => 'search#text'

  post 'vote/' => 'vote#change_vote', as: :vote

  get 'tags/start_with' => 'tags#start_with'

  get 'user/:id' => 'user#show', as: :user
  get 'admin' => 'user#admin'
  post 'user/:id' => 'user#update'
  delete 'user/:id/delete' => 'user#delete'

  get 'creatives/:id/reorder_chapters' => 'creatives#reorder_chapters'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    if user.admin?
      can :manage, :all
    else
      can :update, Creative, :user_id => user.id
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/chapter.rb
class Chapter < ActiveRecord::Base
  belongs_to :creative, :touch => true
end

app/models/creative.rb
class Creative < ActiveRecord::Base
  belongs_to :user
  has_and_belongs_to_many :tags
  has_many :chapters, dependent: :destroy
  has_many :votes, dependent: :destroy
  validates :title, :description, presence: true
  after_save :increase_user_amount
  before_destroy :decrease_user_amount

  private 
    def increase_user_amount
      user.creatives_num += 1
      user.save
    end

    def decrease_user_amount
      user.creatives_num -= 1
      user.save
    end
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_and_belongs_to_many :creatives

  def self.like(str)
    where("value LIKE ? ", "%#{str}%").order(:ammount).take(10)
  end

  def self.most_popular
    order(:ammount => :desc).take(10)    
  end

  def self.get_or_create(tag_value)
    tag = where(:value => tag_value).last
    if tag
      tag.ammount += 1
      tag.save
    else
      tag = new(:value => tag_value)
    end
    return tag
  end

  def decrease
    if self.ammount == 1
      self.destroy
    else
      self.ammount -= 1
      self.save
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
  has_many :creatives, dependent: :destroy

  def self.most_popular
    order(:creatives_num => :desc).take(10)
  end
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :user
  belongs_to :creative, :touch => true
end

app/controllers/chapters_controller.rb
class ChaptersController < ApplicationController
  before_action :set_creative
  before_action :set_chapter, only: [:show, :edit, :update, :destroy]
  after_action :reload_cache, only: [:create, :update, :destroy]

  # GET /chapters
  # GET /chapters.json
  def index
    @chapters = Chapter.all
  end

  # GET /chapters/1
  # GET /chapters/1.json
  def show
  end

  # GET /chapters/new
  def new
    @chapter = @creative.chapters.build
    respond_to do |format|
      format.json { render "_form.html", :layout => false }
    end
  end

  # GET /chapters/1/edit
  def edit
    respond_to do |format|
      format.html { render "edit" }
      format.json { render "_form.html", :layout => false }
    end
  end

  # POST /chapters
  # POST /chapters.json
  def create
    @chapter = @creative.chapters.create(chapter_params)
    @chapter.order = (@creative.chapters.maximum("order") || -1) + 1
    respond_to do |format|
      if @chapter.save
        format.json { render action: 'show', status: :created }
      else
        format.json { render json: @chapter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /chapters/1
  # PATCH/PUT /chapters/1.json
  def update
    respond_to do |format|
      if @chapter.update(chapter_params)
        format.json { render action: 'show' }
      else
        format.json { render json: @chapter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chapters/1
  # DELETE /chapters/1.json
  def destroy
    @chapter.destroy
    respond_to do |format|
      format.json { head :no_content }
    end
  end

  private
    def set_creative
      @creative = Creative.find(params[:creative_id])
    end
    
    def set_chapter
      @chapter = @creative.chapters.find(params[:id])
    end

    def chapter_params
      params.require(:chapter).permit(:title, :content)
    end

    def reload_cache
      expire_fragment([:creative, :show, @creative.id])
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @creatives = Creative.order(:num_of_votes => :desc).paginate(:page => params[:page], :per_page => 7)
    @tags = Tag.most_popular
    @users = User.most_popular
  end

  def switch_theme
    if cookies[:theme] == "flatly"
        cookies[:theme] = "cyborg"
    else
        cookies[:theme] = "flatly"
    end
    redirect_to request.referrer
  end

end

app/controllers/search_controller.rb
class SearchController < ApplicationController

  def tag
    @tag_value = params[:q]
    @creatives = get_creatives_by_tag
  end

  def text
    @creatives = Creative.search(params[:q], :page => params[:page])
  end

  private
    def get_creatives_by_tag
      seeking_tag = Tag.find_by(:value => @tag_value)
      seeking_tag.creatives.paginate(:page => params[:page]) if seeking_tag
    end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  def start_with
    @tags = Tag.like(params[:q])
  end
  
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  before_action :check_rights, only: [:admin, :change, :delete]
  before_action :set_user, only: [:update, :delete]

  def show
    @user = User.find(params[:id])
    @creatives = get_creative
  end

  def admin
    @users = User.order(:username).paginate(:page => params[:page])
  end

  def update
    @user.update(user_params)
    if params[:confirm]
      user.update(:confirmed_at => Time.now)
    end
    redirect_to admin_path
  end

  def delete
    user.destroy
    redirect_to admin_path
  end

  private
    def check_rights
      authorize! :manage, current_user
    end

    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:admin)
    end

    def get_creative
      Creative.where(:user_id => params[:id]).paginate(:page => params[:page])
    end
end

app/controllers/vote_controller.rb
class VoteController < ApplicationController
  before_action :set_vote_and_creative

  def change_vote
    if @creative
      if !@vote
        create_new_vote
        @vote_is_set = "true"
      else
        destroy_vote
      end
    end
    @vote_is_set ||= "false"
  end

  private
    def set_vote_and_creative
      @vote = Vote.where(:creative_id => params[:id], :user_id => current_user.id).first
      @creative = Creative.where(:id => params[:id]).first
    end

    def create_new_vote
      vote = Vote.create(:user_id => current_user.id, :creative_id => params[:id])
      vote.save
      @creative.num_of_votes += 1
      @creative.save
    end

    def destroy_vote
      @vote.destroy
      @creative.num_of_votes -= 1
      @creative.save
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chapters_helper.rb
module ChaptersHelper
end

app/helpers/creatives_helper.rb
module CreativesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/vote_helper.rb
module VoteHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>Creatives Project</title>
    <%= stylesheet_link_tag cookies[:theme], :media => "all" %>
    <%= javascript_include_tag cookies[:theme] %>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
</head>
<body>
    <nav class="navbar navbar-default navbar-static-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <td><%= link_to 'Creatives Project', root_path, :class => "navbar-brand" %></td>
            </div>
            <ul class="nav navbar-nav">

            <form action=<%= url_for search_text_path %> method="GET" class="navbar-form navbar-left" role="search">
                <div class="form-group">
                    <input type="text" class="form-control" placeholder=<%= t("navigation.search") %> name="q">
                </div>
            </form>
            </ul>
            <ul class="nav navbar-nav pull-right">
                <%= render "shared/login_menu" %>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <span class="glyphicon glyphicon-cog"></span>
                    </a>
                    <ul class="dropdown-menu" role="menu">
                        <li>
                            <%= link_to t("navigation.theme"), switch_theme_path, :method => :post %>
                        </li>
                        <li role="presentation" class="divider"></li>
                        <li class="dropdown-header">
                            <%= t("navigation.language") %>
                        </li>
                        <li>
                            <%= link_to t("navigation.language_ru"), request.path +  "?locale=ru" %>
                        </li>
                        <li>
                            <%= link_to t("navigation.language_en"), request.path +  "?locale=en" %>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
    </nav>

    <div class="container main-content">
        <%= yield %>
    </div>

</body>
</html>

app/views/shared/_creatives.html.erb
<% if !@creatives || @creatives.length == 0 %>
<h3>Nothing found :(</h3>
<% else %>
<% @creatives.each do |creative| %>
    <div class="creative">
        <h2 class="text-center"><%= link_to creative.title, creative %><small></small></h2>

        <p><%= creative.description %></p>

        <div class="creative-footer"> 
            <span class="glyphicon glyphicon-calendar"></span><a><%= creative.created_at.strftime("%F") %></a>
            <span class="glyphicon glyphicon-user"></span>
            <%= link_to creative.user.username, "/user/" + creative.user.id.to_s %>
            <span class="glyphicon glyphicon-tags"></span>
            <% creative.tags.each do |tag| %>
                <%= link_to tag.value, search_tag_path + "/?q=" + tag.value %>
            <% end %>
            <% if !user_signed_in? || !creative.votes.where(:user_id => current_user.id).last %>
                <span id=<%= creative.id %> class="vote-button btn btn-default btn-xs pull-right">
                    <span class="glyphicon glyphicon-thumbs-up"></span>
                    <span id="vote"><%= creative.num_of_votes %></span>
                </span> 
            <% else %>
                <span id=<%= creative.id %> class="vote-button btn btn-primary btn-xs pull-right">
                    <span class="glyphicon glyphicon-thumbs-up"></span>
                    <span id="vote"><%= creative.num_of_votes %></span>
                </span> 

            <% end %> 
        </div>
    </div>
    <hr style="width: 50%;"/>
<% end %>

<%= will_paginate @creatives, renderer: BootstrapPagination::Rails %>
<% end %>

app/views/shared/_login_menu.html.erb
<% if user_signed_in? %>
    <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <span class="glyphicon glyphicon-user"></span>
            <%= current_user.username %>
            <b class="caret"></b>
        </a>
        <ul class="dropdown-menu" role="menu">
            <li>
                <a href=<%= url_for new_creative_path %>>
                    <span class="glyphicon glyphicon-plus "></span>
                    <%= t("navigation.write_new") %>
                </a>
            </li>
            <li>
                <%= link_to t("navigation.all_creatives"), "/user/" + (current_user.id).to_s %>
            </li>
            <li>
                <%= link_to t("navigation.edit_profile"), edit_user_registration_path %>
            </li>
            <li class="divider"></li>
            <% if can? :manage, nil %>
                <li>
                    <%= link_to t("navigation.admin_panel"), admin_path %>
                </li>
                <li class="divider"></li>
            <% end %>
            <li>
                <%= link_to t("navigation.sign_out"), destroy_user_session_path, :method => :delete %>
            </li>
        </ul>
    </li>
<% else %>
    <li ><%= link_to t("navigation.login"), new_user_session_path %></li>
    <li ><%= link_to t("navigation.register"), new_user_registration_path %></li>
<% end %>